name: CI

on:
  schedule:
    # Once a day
    - cron: "0 0 * * *"
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always
  REPO_SLUG: "rumpl/containerd-wasi-shims"

jobs: 
  hub:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPO_SLUG }}
          ### on push default branch (main):
          # wasmedge/runwasi:main
          tags: |
            type=sha
          bake-target: meta-helper
          flavor: |
            latest=false
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v2
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: image-cross
          push: ${{ github.event_name != 'pull_request' }}

